### ISSUE TITLE
PowerMock/Mockito Tests are failing after Sorting pom.xml

### ISSUE THREAD

**Issue by razisam** [Ekryd/sortpom#70]
Hello,
After sorting my pom.xml suddenly the tests are not running anymore.
after reverting the pom.xml, it works again.

```
<plugin>
                    <groupId>com.github.ekryd.sortpom</groupId>
                    <artifactId>sortpom-maven-plugin</artifactId>
                    <version>${version.sortpom-maven-plugin}</version>
                    <configuration>
                        <predefinedSortOrder>recommended_2008_06</predefinedSortOrder>
                        <keepBlankLines>true</keepBlankLines>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <sortDependencies>scope,artifactId</sortDependencies>
                        <sortPlugins>groupId,artifactId</sortPlugins>
                        <sortProperties>false</sortProperties>
                        <sortModules>true</sortModules>
                        <createBackupFile>false</createBackupFile>
                        <ignoreLineSeparators>false</ignoreLineSeparators>
                        <nrOfIndentSpace>4</nrOfIndentSpace>
                        <indentBlankLines>false</indentBlankLines>
                    </configuration>
                </plugin>
```

```
java.lang.ExceptionInInitializerError
        at my.project.pkg.esb.dispatch.MessageDispatcherTest.setUp(MessageDispatcherTest.java:102)
Caused by: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.StackTraceCleanerProvider (alternate: null)
        at my.project.pkg.esb.dispatch.MessageDispatcherTest.setUp(MessageDispatcherTest.java:102)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.StackTraceCleanerProvider implementation declared in java.lang.CompoundEnumeration@47cb2624
        at my.project.pkg.esb.dispatch.MessageDispatcherTest.setUp(MessageDispatcherTest.java:102)
Caused by: java.lang.ClassCastException: **Cannot cast org.powermock.api.mockito.internal.exceptions.StackTraceCleanerProvider to org.mockito.plugins.StackTraceCleanerProvider**
        at my.project.pkg.esb.dispatch.MessageDispatcherTest.setUp(MessageDispatcherTest.java:102)
```

**Comment by razisam** [comment]
i am using 2.10.0 release

**Comment by Ekryd** [comment]
Hi,
There are three settings that affect the actual build:

- sortDependencies may affect in which order classes are added to the build if a library is included multiple times. This may happen i a library is included both directly and indirectly in the pom.

- sortPlugins may affect in which order Maven plugins are run in a build. This may happen if multiple plugins are run in the same Maven phase.

- sortModules may cause a build to fail if the modules are indirectly referencing each other.

Use the same SortPom configuration as before and remove the sortDependencies, sortPlugins and sortModules parameter. The build should now run fine. 
Add parameters back to the SortPom configuration one by one to see which one causes the build error.

When the guilty parameter has been identified, I can help you solve the actual problem.

**Comment by razisam** [comment]
when using
`                        <sortDependencies>scope,artifactId</sortDependencies>`
the ClassCastException mentioned above appears.

**Comment by razisam** [comment]
hmmm, just saw the "Dependency Management problem"-Headline here: https://github.com/Ekryd/sortpom/wiki/SortDependencies

i see, so my problem is, that i do not configure "scope" in the dependencies because i already have this in the "depenendy management".

`<sortDependencies>groupId,artifactId</sortDependencies>`
also causes the ClassCastException.

**Comment by razisam** [comment]
so the solution is to add "scope" also redundant to the "dependencies"?
is that correct?

**Comment by razisam** [comment]
i added scope-tag to every dependency.
now, i can add:
`<sortDependencies>scope,groupId</sortDependencies>`
but as soon as i sort by "artifactId", the tests are throwing ClassCastException (mentioned above) again.

**Comment by razisam** [comment]
just identified the part in the pom.xml which causes issue.

this sort order of depenendecies is working:
```
            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4-legacy</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4-rule</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-api-mockito2</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-reflect</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-api-easymock</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-classloading-xstream</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>
```

**Comment by razisam** [comment]
After sorting also by "artifactId" (`<sortDependencies>scope,type,groupId,artifactId</sortDependencies>`) it looks like this and crashes:
```
<dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-api-easymock</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-api-mockito2</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-classloading-xstream</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4-legacy</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4-rule</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-reflect</artifactId>
                <version>${version.powermock}</version>
                <scope>test</scope>
            </dependency>
```

**Comment by razisam** [comment]
Analyze finished:
This is what the plugin is doing, when it is sorting:
```
<dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-api-easymock</artifactId>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-api-mockito2</artifactId>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-classloading-xstream</artifactId>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4</artifactId>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4-legacy</artifactId>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4-rule</artifactId>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-reflect</artifactId>
                <scope>test</scope>
            </dependency>
```

**Comment by razisam** [comment]
the ClassCastException appears, WHEN `powermock-api-easymock` is located BEFORE `powermock-api-mockito2`

**Comment by razisam** [comment]
this is somehow sorted, and also working
only `powermock-api-easymock` moved down

```
<dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-classloading-xstream</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4-legacy</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4-rule</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- TODESSTRAFE, FUER DENJENIGEN, DER DIESE DEPENDENCY WOANDERS HIN VERSCHIEBT -->
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-easymock</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- /TODESSTRAFE:ENDE -->

        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-reflect</artifactId>
            <scope>test</scope>
        </dependency>
```

**Comment by Ekryd** [comment]
I think that you found the problem, when powermock-api-easymock is located before powermock-api-mockito2. So the problem is most likely that the dependencies affect each other because SortPom sorted them in a specific way. I don't think that the actual plugin code affects the test runs.

You should be able set <sortDependencies>scope,groupId</sortDependencies> to preserve the order of the powermock dependencies.

The number of dependencies makes me think, do you really need them all? Maybe some of them can be omitted to avoid conflicts.

I saw that the powermock-api-mockito2 dependency included mockito core. Do you have other dependencies that also include Mockito (Directly or Spring boot etc)?

If you really want to sort the artifacts, then you may need to exclude secondary dependencies in the pom file. Have a look at https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html.

**Comment by Ekryd** [comment]
There is also an option to omit sorting a specific dependency by using https://github.com/Ekryd/sortpom/wiki/IgnoringSections

**Comment by razisam** [comment]
thanks for the advices and hints. i'm getting rid of easymock. that is the best way.
ticket can be closed.

other Question: what is your experience with sortpom-plugin plus Jenkins CI. Currently  i have to tell my Jenkins-Job to clean checkout from SVN, otherwise there will be always an merge conflict in pom.xml when run the job the second time.

**Comment by Ekryd** [comment]
I have been using SortPom together with Jenkins, but then I use the verify goal instead. Each developer must sort the pom (often just by building the project) before they make a checkin. 

The verify goal will fail the build if the pom is not sorted, same as it fails the build if tests are not successful.
